[package]
name = "liu-bbs"
description = "a bbs application api server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.19", features = ["derive"] }
rocket = { version = "0.5.0-rc.2", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
mongodb = "2.3.0"
thiserror = "1.0"

[dependencies.tokio]
version = "1.20.1"
features = ["fs", "io-std", "io-util", "rt-multi-thread", "sync", "signal"]